grammar: ../cqp.ebnf
default: cdli
n_results: 50
api:
  port: 8088
  host: 127.0.0.1
sparql:
  host: http://127.0.0.1:3030/
  endpoint: test/query
corpora:
  ud-en:
    name: Universal Dependencies English (test)
    iri: http://acoli.cs.uni-frankfurt.de/corpora/ud-en
    prefixes:
      conll: http://ufal.mff.cuni.cz/conll2009-st/task-description.html#
      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
      terms: http://purl.org/acoli/open-ie/
      nif: http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      system: http://purl.org/olia/system.owl#
      olia:  http://purl.org/olia/olia.owl#
      powla: http://purl.org/powla/powla.owl#
      eanc: http://purl.org/olia/eanc.owl#
      xsd: http://www.w3.org/2001/XMLSchema#
  cdli:
    name: CDLI
    iri: https://github.com/cdli-gh/Multilayer-Annotation-Query-Tool/
    file-host: https://cdli.ucla.edu/ 
    prefixes:
      conll: http://ufal.mff.cuni.cz/conll2009-st/task-description.html#
      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
      terms: http://purl.org/acoli/open-ie/
      nif: http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      system: http://purl.org/olia/system.owl#
      olia:  http://purl.org/olia/olia.owl#
      powla: http://purl.org/powla/powla.owl#
      eanc: http://purl.org/olia/eanc.owl#
      xsd: http://www.w3.org/2001/XMLSchema#
    fields:
      ID:
        name: ID
        query: conll:ID
        disabled: false
        type: integer
        multivalued: false
      CDLI_ID:
        name: CDLI_ID
        query: conll:CDLI_ID
        disabled: false
        type: suggest
        multivalued: false
        values:
          - "o.1.1"
          - "r.3.5"
          - "l.1.1"
          - "s1.col1.1.1"
          - "s1.2.1"
      FORM:
        name: FORM
        query: conll:FORM
        disabled: false
        type: suggest
        multivalued: false
        values:
          - "udu"
          - "sze"
          - "lugal"
          - "lu2"
          - "mu"
          - "mu-na-du3"
      LEMMA:
        name: LEMMA
        query: conll:LEMMA
        disabled: false
        type: suggest
        multivalued: false
        values:
          - "udu"
          - "sze"
          - "lugal"
          - "lu2"
          - "mu"
          - "du3"
      UPOSTAG:
        name: UPOSTAG
        query: conll:UPOSTAG
        disabled: false
        type: list
        multivalued: false
        values:
          - "ADJ"
          - "ADP"
          - "ADV"
          - "CCONJ"
          - "DET"
          - "INTJ"
          - "NUM"
          - "NOUN"
          - "PROPN"
          - "VERB"
      XPOSTAG:
        name: XPOSTAG
        query: conll:XPOSTAG
        disabled: false
        type: list
        multivalued: false
        values:
          - "AJ"
          - "AV"
          - "NU"
          - "CNJ"
          - "DET"
          - "J"
          - "N"
          - "V"
          - "PRP"
          - "DN"
          - "EN"
          - "GN"
          - "MN"
          - "PN"
          - "RN"
          - "SN"
          - "TN"
          - "WN"
          - "AN"
          - "CN"
          - "FN"
          - "LN"
          - "ON"
          - "QN"
          - "YN"
      FEATS:
        name: FEATS
        query: conll:FEATS
        disabled: false
        type: list
        multivalued: true
        separator: "|"
        values:
          - ".*Animacy=Hum.*"
          - ".*Animacy=Nhum.*"
          - ".*Case=Abs.*"
          - ".*Case=Gen.*"
          - ".*Case=Erg.*"
          - ".*Case=Abl.*"
          - ".*Number=Plur.*"
          - ".*Number=Sing.*"
          - ".*Aspect=Prosp.*"
          - ".*Mood=Opt.*"
          - ".*Person=0.*"
          - ".*Person=1.*"
          - ".*Person=2.*"
          - ".*Person=3.*"
          - ".*Person=4.*"
          - ".*Polarity=Opt.*"
          - ".*Verb Form=Fin.*"
          - ".*Voice=Mid.*"
          